In [2]:
import pandas as pd
import numpy as np
import folium
import geopandas
import os

### Óbitos em Sao Paulo

In [7]:
obitos_sp = pd.read_csv('../dados/SP/obitos_publico.csv', delimiter=';', encoding='unicode_escape')

In [8]:
obitos_sp.head()

,Id da Delegacia (RDO),Número do Bo (RDO),Ano do BO (RDO),Data do Óbito,Data do Acidente,Tipo de via,Dia do óbito,Mês do Óbito,Mês Óbito Descrição,Ano do Óbito,...,Tipo do veículo da vítima,Tipo de vítima,Local do óbito,Tipo de acidente,Sub Tipo do Acidente,Sexo,Faixa etária,Idade da vítima,Outro Veículo Envolvido,Tempo entre o Acidente e o Óbito
0,120300,1005409502,2023,2023-04-30,2023-04-30,Vias Municipais,30,4,ABRIL,2023,...,MOTOCICLETA,CONDUTOR,VIA,CHOQUE,ÁRVORE,MASCULINO,18-24,22,NÃO HÁ,Até 30 dias
1,100907,1005405590,2023,2023-04-30,2022-11-24,Vias Municipais,30,4,ABRIL,2023,...,MOTOCICLETA,CONDUTOR,ESTABELECIMENTO DE SAUDE,COLISAO,FRONTAL,MASCULINO,18-24,18,AUTOMOVEL,Mais de 30 dias
2,120505,1005409294,2023,2023-04-30,2023-04-30,Vias Municipais,30,4,ABRIL,2023,...,MOTOCICLETA,CONDUTOR,ESTABELECIMENTO DE SAUDE,ATROPELAMENTO,ANIMAL,MASCULINO,40-44,42,NÃO HÁ,Até 30 dias
3,10326,1005403023,2023,2023-04-30,2023-04-30,Vias Municipais,30,4,ABRIL,2023,...,MOTOCICLETA,CONDUTOR,VIA,COLISAO,LATERAL,MASCULINO,35-39,35,AUTOMOVEL,Até 30 dias
4,10211,1005402331,2023,2023-04-30,2023-04-30,Vias Municipais,30,4,ABRIL,2023,...,MOTOCICLETA,CONDUTOR,ESTABELECIMENTO DE SAUDE,OUTROS,TOMBAMENTO VEÍCULO DE 2 RODAS,MASCULINO,18-24,20,NÃO HÁ,Até 30 dias

In [39]:
obitos_sp.columns

Index(['Id da Delegacia (RDO)', 'Número do Bo (RDO)', 'Ano do BO (RDO)',
       'Data do Óbito', 'Data do Acidente', 'Tipo de via', 'Dia do óbito',
       'Mês do Óbito', 'Mês Óbito Descrição', 'Ano do Óbito',
       'Ano/Mês do Óbito', 'Dia da Semana', 'Hora do Acidente', 'Turno',
       'Município', 'Região Administrativa', 'Logradouro', 'Númeral / KM',
       'Jurisdição', 'Administração', 'Conservação',
       'Tipo do local da ocorrência', 'LAT_(GEO)', 'LONG_(GEO)',
       'Tipo do veículo da vítima', 'Tipo de vítima', 'Local do óbito',
       'Tipo de acidente', 'Sub Tipo do Acidente', 'Sexo', 'Faixa etária',
       'Idade da vítima', 'Outro Veículo Envolvido',
       'Tempo entre o Acidente e o Óbito'],
      dtype='object')

In [50]:
obitos_sp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46174 entries, 0 to 46173
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Id da Delegacia (RDO)             46174 non-null  int64
 1   Número do Bo (RDO)                46174 non-null  int64
 2   Ano do BO (RDO)                   46174 non-null  int64
 3   Data do Óbito                     46174 non-null  object
 4   Data do Acidente                  46174 non-null  object
 5   Tipo de via                       46174 non-null  object
 6   Dia do óbito                      46174 non-null  int64
 7   Mês do Óbito                      46174 non-null  int64
 8   Mês Óbito Descrição               46174 non-null  object
 9   Ano do Óbito                      46174 non-null  int64
 10  Ano/Mês do Óbito                  46174 non-null  float64
 11  Dia da Semana                     46174 non-null  object
 12  Hora do Acidente                  46174 non-null  object
 13  Turno                             46174 non-null  object
 14  Município                         46174 non-null  object
 15  Região Administrativa             46174 non-null  object
 16  Logradouro                        46174 non-null  object
 17  Númeral / KM                      46174 non-null  object
 18  Jurisdição                        46174 non-null  object
 19  Administração                     46174 non-null  object
 20  Conservação                       46174 non-null  object
 21  Tipo do local da ocorrência       46174 non-null  object
 22  LAT_(GEO)                         46174 non-null  object
 23  LONG_(GEO)                        46174 non-null  object
 24  Tipo do veículo da vítima         46174 non-null  object
 25  Tipo de vítima                    46174 non-null  object
 26  Local do óbito                    46174 non-null  object
 27  Tipo de acidente                  46174 non-null  object
 28  Sub Tipo do Acidente              29386 non-null  object
 29  Sexo                              46174 non-null  object
 30  Faixa etária                      46174 non-null  object
 31  Idade da vítima                   46174 non-null  object
 32  Outro Veículo Envolvido           34742 non-null  object
 33  Tempo entre o Acidente e o Óbito  46174 non-null  object
dtypes: float64(1), int64(6), object(27)
memory usage: 12.0+ MB

In [51]:
obitos_sp['Ano do BO (RDO)'].unique()

array([2023, 2022, 2021, 2020, 2019, 2012, 2015, 2016, 2018, 2017, 2014,
       2013, 2011], dtype=int64)

### Acidentes Nao Fatais

In [10]:
nao_fatais = pd.read_csv("../dados/SP/acidentes_naofatais.csv", delimiter=";", encoding='unicode_escape')

In [55]:
nao_fatais.head()

,ID,Data do Acidente,Dia do Acidente,Mês do Acidente,Ano do Acidente,Ano/Mês do Acidente,Dia da Semana,Hora do Acidente,Turno,Município,...,Serviço de Atendimento - PRF,Serviço de Atendimento - Radio Patrulha,Servciço de Atendimento - CPTRAN,Tipo de Via,Tipo de Acidente - Atropelamento (Pedestre),Tipo de Acidente - Atropelamento (Animal),Tipo de Acidente - Choque,Tipo de Acidente - Colisão,Tipo de Acidente - Outros tipos de Acidente,Turno + Dia de Semana
0,9144205,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,21:45,NOITE,SAO VICENTE,...,NÃO,SIM,NÃO,Vias Municipais,0,0,0,1,0,NOITE DE DOMINGO
1,9144185,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,20:47,NOITE,ADAMANTINA,...,NÃO,SIM,NÃO,Rodovias,0,0,0,0,1,NOITE DE DOMINGO
2,9144215,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,21:54,NOITE,GUARULHOS,...,NÃO,SIM,NÃO,Vias Municipais,0,0,0,1,0,NOITE DE DOMINGO
3,9144219,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,22:11,NOITE,ITAPEVA,...,NÃO,SIM,NÃO,Vias Municipais,0,0,0,1,0,NOITE DE DOMINGO
4,9144220,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,22:14,NOITE,MONTE APRAZIVEL,...,NÃO,SIM,NÃO,NAO DISPONIVEL,0,0,1,0,0,NOITE DE DOMINGO

In [57]:
nao_fatais.columns

Index(['ID', 'Data do Acidente', 'Dia do Acidente', 'Mês do Acidente',
       'Ano do Acidente', 'Ano/Mês do Acidente', 'Dia da Semana',
       'Hora do Acidente', 'Turno', 'Município', 'Batalhão de Trânsito',
       'Companhia de Trânsito', 'Região Administrativa', 'Logradouro',
       'Numero/KM', 'Jurisdição', 'Administração', 'Conservação', 'LAT_(GEO)',
       'LONG_(GEO)', 'Condições Climáticas', 'Iluminação', 'Mão de direção',
       'Obras na pista', 'Relevo', 'Superfície da via', 'Tipo de pavimento',
       'Tipo de pista', 'Traçado', 'Veículos Envolvidos - Bicicleta',
       'Veículos Envolvidos - Caminhão', 'Veículos Envolvidos - Automóvel',
       'Veículos Envolvidos - Motocicleta', 'Veículos Envolvidos - Ônibus',
       'Veículos Envolvidos - Pedestre', 'Pessoas Envolvidas - Grave',
       'Pessoas Envolvidas - Ileso', 'Pessoas Envolvidas - Leve',
       'Serviço de Atendimento - Bombeiro', 'Serviço de Atendimento - PMRV',
       'Serviço de Atendimento - PRF',
       'Serviço de Atendimento - Radio Patrulha',
       'Servciço de Atendimento - CPTRAN', 'Tipo de Via',
       'Tipo de Acidente - Atropelamento (Pedestre)',
       'Tipo de Acidente - Atropelamento (Animal)',
       'Tipo de Acidente - Choque', 'Tipo de Acidente - Colisão',
       'Tipo de Acidente - Outros tipos de Acidente', 'Turno + Dia de Semana'],
      dtype='object')

In [58]:
nao_fatais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770184 entries, 0 to 770183
Data columns (total 50 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   ID                                           770184 non-null  int64
 1   Data do Acidente                             770184 non-null  object
 2   Dia do Acidente                              770184 non-null  int64
 3   Mês do Acidente                              770184 non-null  object
 4   Ano do Acidente                              770184 non-null  int64
 5   Ano/Mês do Acidente                          770184 non-null  float64
 6   Dia da Semana                                770184 non-null  object
 7   Hora do Acidente                             770184 non-null  object
 8   Turno                                        770184 non-null  object
 9   Município                                    770184 non-null  object
 10  Batalhão de Trânsito                         0 non-null       float64
 11  Companhia de Trânsito                        0 non-null       float64
 12  Região Administrativa                        770184 non-null  object
 13  Logradouro                                   770181 non-null  object
 14  Numero/KM                                    770184 non-null  object
 15  Jurisdição                                   770184 non-null  object
 16  Administração                                770184 non-null  object
 17  Conservação                                  770184 non-null  object
 18  LAT_(GEO)                                    697137 non-null  object
 19  LONG_(GEO)                                   697055 non-null  object
 20  Condições Climáticas                         770184 non-null  object
 21  Iluminação                                   770184 non-null  object
 22  Mão de direção                               770184 non-null  object
 23  Obras na pista                               770184 non-null  object
 24  Relevo                                       770184 non-null  object
 25  Superfície da via                            770184 non-null  object
 26  Tipo de pavimento                            770184 non-null  object
 27  Tipo de pista                                770184 non-null  object
 28  Traçado                                      770184 non-null  object
 29  Veículos Envolvidos - Bicicleta              770184 non-null  int64
 30  Veículos Envolvidos - Caminhão               770184 non-null  int64
 31  Veículos Envolvidos - Automóvel              770184 non-null  int64
 32  Veículos Envolvidos - Motocicleta            770184 non-null  int64
 33  Veículos Envolvidos - Ônibus                 770184 non-null  int64
 34  Veículos Envolvidos - Pedestre               770184 non-null  int64
 35  Pessoas Envolvidas - Grave                   770184 non-null  int64
 36  Pessoas Envolvidas - Ileso                   770184 non-null  int64
 37  Pessoas Envolvidas - Leve                    770184 non-null  int64
 38  Serviço de Atendimento - Bombeiro            770184 non-null  object
 39  Serviço de Atendimento - PMRV                770184 non-null  object
 40  Serviço de Atendimento - PRF                 770184 non-null  object
 41  Serviço de Atendimento - Radio Patrulha      770184 non-null  object
 42  Servciço de Atendimento - CPTRAN             770184 non-null  object
 43  Tipo de Via                                  770184 non-null  object
 44  Tipo de Acidente - Atropelamento (Pedestre)  770184 non-null  int64
 45  Tipo de Acidente - Atropelamento (Animal)    770184 non-null  int64
 46  Tipo de Acidente - Choque                    770184 non-null  int64
 47  Tipo de Acidente - Colisão                   770184 non-null  int64
 48  Tipo de Acidente - Outros tipos de Acidente  770184 non-null  int64
 49  Turno + Dia de Semana                        770184 non-null  object
dtypes: float64(3), int64(17), object(30)
memory usage: 293.8+ MB

### Acidentes Fatais

In [11]:
acid_fatais = pd.read_excel("../dados/SP/acidentes_fatais.xlsx")

C:\Users\danil\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [60]:
acid_fatais.head()

,ID,Id Delegacia (RDO),Número BO (RDO),Ano BO (RDO),Data do Acidente,Dia do Acidente,Mês do Acidente,Ano do Acidente,Ano/Mês do Acidente,Dia da semana,...,Iluminação da via (SIOPM),Superfície da Via (SIOPM),Tipo de pista (SIOPM),Outro Veículo Envolvido,Tipo de via,Condições Climáticas (SIOPM),Sentido da Via (SIOPM),Limite da velocidade da via (SIOPM),Quantidade de vítimas,Tempo entre o Acidente e as Mortes
0,3084163,10211,1005402331,2023,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,...,NAO DISPONIVEL,NAO DISPONIVEL,NAO DISPONIVEL,NÃO HÁ,Vias Municipais,NAO DISPONIVEL,NAO DISPONIVEL,NAO DISPONIVEL,1,Até 30 dias
1,3084303,10216,1005408855,2023,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,...,NAO DISPONIVEL,NAO DISPONIVEL,NAO DISPONIVEL,AUTOMOVEL,Vias Municipais,NAO DISPONIVEL,NAO DISPONIVEL,NAO DISPONIVEL,1,Até 30 dias
2,3084326,10326,1005403023,2023,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,...,NAO DISPONIVEL,NAO DISPONIVEL,NAO DISPONIVEL,AUTOMOVEL,Vias Municipais,NAO DISPONIVEL,NAO DISPONIVEL,NAO DISPONIVEL,1,Até 30 dias
3,3084306,30206,1005406617,2023,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,...,LUZ SOLAR,SECA,DUPLA,NÃO HÁ,Rodovias,BOM,OESTE,Entre 90 e 100km/h,1,Até 30 dias
4,3084305,30406,1005402823,2023,2023-04-30,30,ABRIL,2023,2023.04,DOMINGO,...,NAO DISPONIVEL,NAO DISPONIVEL,NAO DISPONIVEL,AUTOMOVEL,Vias Municipais,NAO DISPONIVEL,NAO DISPONIVEL,NAO DISPONIVEL,1,Até 30 dias

In [61]:
acid_fatais.columns

Index(['ID', 'Id Delegacia (RDO)', 'Número BO (RDO)', 'Ano BO (RDO)',
       'Data do Acidente', 'Dia do Acidente', 'Mês do Acidente',
       'Ano do Acidente', 'Ano/Mês do Acidente', 'Dia da semana',
       'Hora do Acidente', 'Turno', 'Município', 'Região Administrativa',
       'Logradouro', 'Numeral / KM', 'Jurisdição', 'Administração',
       'Conservação', 'Tipo do Local do Acidente', 'Lat (GEO)', 'Long (GEO)',
       'Iluminação da via (SIOPM)', 'Superfície da Via (SIOPM)',
       'Tipo de pista (SIOPM)', 'Outro Veículo Envolvido', 'Tipo de via',
       'Condições Climáticas (SIOPM)', 'Sentido da Via (SIOPM)',
       'Limite da velocidade da via (SIOPM)', 'Quantidade de vítimas',
       'Tempo entre o Acidente e as Mortes'],
      dtype='object')

In [62]:
acid_fatais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43263 entries, 0 to 43262
Data columns (total 32 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ID                                   43263 non-null  int64
 1   Id Delegacia (RDO)                   43263 non-null  int64
 2   Número BO (RDO)                      43263 non-null  int64
 3   Ano BO (RDO)                         43263 non-null  int64
 4   Data do Acidente                     43263 non-null  datetime64[ns]
 5   Dia do Acidente                      43263 non-null  int64
 6   Mês do Acidente                      43263 non-null  object
 7   Ano do Acidente                      43263 non-null  int64
 8   Ano/Mês do Acidente                  43263 non-null  float64
 9   Dia da semana                        43263 non-null  object
 10  Hora do Acidente                     43263 non-null  object
 11  Turno                                43263 non-null  object
 12  Município                            43263 non-null  object
 13  Região Administrativa                43263 non-null  object
 14  Logradouro                           43263 non-null  object
 15  Numeral / KM                         43263 non-null  object
 16  Jurisdição                           43263 non-null  object
 17  Administração                        43263 non-null  object
 18  Conservação                          43263 non-null  object
 19  Tipo do Local do Acidente            43263 non-null  object
 20  Lat (GEO)                            43263 non-null  object
 21  Long (GEO)                           43263 non-null  object
 22  Iluminação da via (SIOPM)            43263 non-null  object
 23  Superfície da Via (SIOPM)            43263 non-null  object
 24  Tipo de pista (SIOPM)                43263 non-null  object
 25  Outro Veículo Envolvido              32588 non-null  object
 26  Tipo de via                          43263 non-null  object
 27  Condições Climáticas (SIOPM)         43263 non-null  object
 28  Sentido da Via (SIOPM)               43263 non-null  object
 29  Limite da velocidade da via (SIOPM)  43263 non-null  object
 30  Quantidade de vítimas                43263 non-null  int64
 31  Tempo entre o Acidente e as Mortes   43263 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(7), object(23)
memory usage: 10.6+ MB

In [64]:
acid_fatais['Município'].unique()

array(['SAO PAULO', 'ITAPECERICA DA SERRA', 'IBITINGA', 'SARAPUI',
       'IBIUNA', 'SANTOS', 'CUBATAO', 'SANTA MARIA DA SERRA', 'GARCA',
       'ASSIS', 'JAMBEIRO', 'GUARULHOS', 'BERTIOGA', 'SAO SEBASTIAO',
       'AVANHANDAVA', 'AMERICANA', 'JABOTICABAL', 'RIBEIRAO PRETO',
       'CATANDUVA', 'LARANJAL PAULISTA', 'ITAPETININGA', 'SAO VICENTE',
       'PIRACICABA', 'SANTA FE DO SUL', 'SAO JOSE DO RIO PRETO',
       'SOROCABA', 'MATAO', 'CAPAO BONITO', 'COSMOPOLIS',
       'CAMPO LIMPO PAULISTA', 'JUNDIAI', 'PRESIDENTE PRUDENTE',
       'SAO JOSE DOS CAMPOS', 'SAO ROQUE', 'SILVEIRAS', 'CAJATI',
       'PIRAPORA DO BOM JESUS', 'SANTANA DE PARNAIBA', 'OSASCO',
       'PORTO FELIZ', 'SAO BERNARDO DO CAMPO', 'MAUA', 'UBATUBA',
       'CAJAMAR', 'ARARAS', 'OURINHOS', 'ELISIARIO', 'URANIA', 'JALES',
       'JARDINOPOLIS', 'CESARIO LANGE', 'JACAREI', 'VARGEM GRANDE DO SUL',
       'CAMPINAS', 'ALVARES MACHADO', 'OLIMPIA', 'ITUVERAVA',
       'NOVO HORIZONTE', 'INDAIATUBA', 'CACAPAVA', 'SUZANO', 'ITAPEVI',
       'CARAPICUIBA', 'PERUIBE', 'ARACATUBA', 'PAULINIA', 'MONTE MOR',
       'BRAGANCA PAULISTA', 'SERTAOZINHO', 'SAO CARLOS', 'SANTO ANDRE',
       'CAPIVARI', 'MARILIA', 'PORTO FERREIRA', 'SANTA ISABEL',
       'PENAPOLIS', 'MARTINOPOLIS', 'PRESIDENTE VENCESLAU', 'FRANCA',
       'CRAVINHOS', 'TREMEMBE', 'BIRIGUI', 'SANTA BARBARA D OESTE',
       'MOGI MIRIM', 'NATIVIDADE DA SERRA', 'DIADEMA', 'ATIBAIA',
       'SANTA CRUZ DA ESPERANCA', 'ICEM', 'FERNANDOPOLIS',
       'ITAQUAQUECETUBA', 'GUZOLANDIA', 'PIRAJUI', 'AMPARO',
       'NAZARE PAULISTA', 'PACAEMBU', 'BATATAIS', 'PEDREGULHO',
       'MIGUELOPOLIS', 'ALUMINIO', 'SALESOPOLIS', 'PINDAMONHANGABA',
       'GUARAREMA', 'TAPIRATIBA', 'SANTA CRUZ DAS PALMEIRAS',
       'JOANOPOLIS', 'QUINTANA', 'SANTA RITA DO PASSA QUATRO',
       'ARTUR NOGUEIRA', 'PALMITAL', 'PEDERNEIRAS', 'LIMEIRA', 'URUPES',
       'IBIRA', 'APARECIDA', 'CACHOEIRA PAULISTA', 'MOGI GUACU',
       'PARAPUA', 'TAUBATE', 'REGISTRO', 'BARRETOS',
       'SANTA ROSA DE VITERBO', 'LAVRINHAS', 'COTIA', 'VOTUPORANGA',
       'PIEDADE', 'SALTO', 'BARUERI', 'BARRA DO TURVO', 'VALINHOS',
       'RANCHARIA', 'CAJOBI', 'MONTE ALTO', 'ANDRADINA', 'PIRASSUNUNGA',
       'SUMARE', 'PINHALZINHO', 'ORLANDIA', 'VOTORANTIM',
       'MOGI DAS CRUZES', 'GUARUJA', 'HORTOLANDIA', 'ITAI', 'ARUJA',
       'FRANCO DA ROCHA', 'ILHABELA', 'DRACENA', 'ARARAQUARA', 'INDIANA',
       'TATUI', 'PRAIA GRANDE', 'JAU', 'CONCHAL', 'VARZEA PAULISTA',
       'BAURU', 'AGUAS DE LINDOIA', 'SAO JOAO DA BOA VISTA', 'PEDREIRA',
       'JARINU', 'ITAPIRA', 'TAQUARITINGA', 'UBARANA', 'BOCAINA',
       'BOTUCATU', 'PONTAL', 'ITU', 'MONGAGUA', 'ITUPEVA',
       'SANTA CRUZ DO RIO PARDO', 'RESTINGA', 'TANABI', 'IPERO',
       'EMBU DAS ARTES', 'ITANHAEM', 'RIO DAS PEDRAS',
       'EUCLIDES DA CUNHA PAULISTA', 'UCHOA', 'CERQUILHO', 'SAO MANUEL',
       'POMPEIA', 'TIMBURI', 'ESTRELA DO NORTE', 'PIRAPOZINHO',
       'PEREIRAS', 'TIETE', 'CUNHA', 'TUPA', 'SAO PEDRO', 'CORDEIROPOLIS',
       'RIO CLARO', 'IRAPUA', 'LORENA', 'JAGUARIUNA', 'DOIS CORREGOS',
       'RIOLANDIA', 'GUAICARA', 'BURI', 'CLEMENTINA', 'ITOBI', 'PIRAJU',
       'POPULINA', 'CANANEIA', 'CAIEIRAS', 'NOVA EUROPA', 'ELDORADO',
       'PINDORAMA', 'GUAPIARA', 'FRANCISCO MORATO', 'IGARACU DO TIETE',
       'ENGENHEIRO COELHO', 'MIRANDOPOLIS', 'SAO SEBASTIAO DA GRAMA',
       'ELIAS FAUSTO', 'LEME', 'BARRINHA', 'SAO MIGUEL ARCANJO', 'MOCOCA',
       'PIRACAIA', 'CAPELA DO ALTO', 'BENTO DE ABREU', 'ILHA SOLTEIRA',
       'ITATIBA', 'TAQUARIVAI', 'MONTE APRAZIVEL', 'BILAC', 'IPIGUA',
       'GENERAL SALGADO', 'SOCORRO', 'ITAPOLIS', 'ARACOIABA DA SERRA',
       'SAO CAETANO DO SUL', 'ALTO ALEGRE', 'LINS', 'BARRA BONITA',
       'PORANGABA', 'PILAR DO SUL', 'ARACARIGUAMA', 'TABOAO DA SERRA',
       'ESPIRITO SANTO DO PINHAL', 'MIRACATU', 'PEREIRA BARRETO',
       'ITATINGA', 'JUQUITIBA', 'CABREUVA', 'GUAPIACU', 'VALENTIM GENTIL',
       'AURIFLAMA', 'AGUAI', 'TARUMA', 'GUATAPARA', 'FLOREAL', 'BANANAL',
       'NIPOA', 'SERRANA', 'CRISTAIS PAULISTA', 'SAO SIMAO',
       'SALTO DE PIRAPORA', 'LENCOIS PAULISTA', 'SERRA NEGRA',
       'BEBEDOURO', 'ONDA VERDE', 'GUARATINGUETA', 'MORRO AGUDO',
       'ALAMBARI', 'CARAGUATATUBA', 'SANTA GERTRUDES', 'PRADOPOLIS',
       'OCAUCU', 'COLINA', 'FLORINEA', 'ZACARIAS', 'RIBEIRA', 'ITARARE',
       'ANHUMAS', 'GUAIRA', 'PATROCINIO PAULISTA', 'CAMPOS DO JORDAO',
       'REGENTE FEIJO', 'PRESIDENTE EPITACIO', 'ADOLFO', 'TERRA ROXA',
       'RINOPOLIS', 'TEODORO SAMPAIO', 'PALMEIRA D OESTE', 'SAGRES',
       'GUARIBA', 'PONTALINDA', 'SANTA ADELIA', 'NOVA ODESSA',
       'JOSE BONIFACIO', 'TAQUARITUBA', 'ANHEMBI', 'CERQUEIRA CESAR',
       'BOM JESUS DOS PERDOES', 'PARANAPANEMA', 'RIBEIRAO PIRES',
       'SAO LOURENCO DA SERRA', 'IACANGA', 'ITARIRI',
       'MONTE AZUL PAULISTA', 'MARABA PAULISTA', 'BARBOSA',
       'SALTO GRANDE', 'IBATE', 'NOVA GRANADA', 'BRODOWSKI', 'ECHAPORA',
       'OSVALDO CRUZ', 'CEDRAL', 'PEDRANOPOLIS', 'AVARE',
       'SANTO ANTONIO DO PINHAL', 'CHARQUEADA', 'ITAPEVA',
       'SANTO ANTONIO DA ALEGRIA', 'QUELUZ', 'IGUAPE', 'SALTINHO',
       'JANDIRA', 'TRES FRONTEIRAS', 'PIRATININGA', 'IACRI', 'PIQUETE',
       'MAIRIPORA', 'MIRASSOL', 'SEVERINIA', 'BADY BASSITT', 'CAJURU',
       'NHANDEARA', 'IPUA', 'SALES', 'ARANDU', 'JUQUIA', 'ITAJOBI',
       'SANTO ANTONIO DE POSSE', 'BOM SUCESSO DE ITARARE', 'LOUVEIRA',
       'COSMORAMA', 'PARAGUACU PAULISTA', 'MACATUBA', 'ITIRAPUA',
       'IGARATA', 'ARAMINA', 'SAO JOSE DA BELA VISTA', 'TABAPUA',
       'ROSEIRA', 'PEDRO DE TOLEDO', 'EMBU-GUACU', 'VITORIA BRASIL',
       'BROTAS', 'AGUAS DA PRATA', 'CHAVANTES', 'ADAMANTINA', 'DUMONT',
       'FERRAZ DE VASCONCELOS', 'AREALVA', 'TABATINGA',
       'SAO LUIS DO PARAITINGA', 'TUIUTI', 'MARACAI', 'GUAREI',
       'TORRINHA', 'PLATINA', 'LUCELIA', 'GUARARAPES', 'JACUPIRANGA',
       'ITIRAPINA', 'JABORANDI', 'BARRA DO CHAPEU', 'BORBOREMA',
       'ESTRELA D OESTE', 'NOVAIS', 'PIRANGI', 'BOFETE', 'VINHEDO',
       'SERRA AZUL', 'DESCALVADO', 'MAIRINQUE', 'RIBEIRAO BRANCO',
       'BOA ESPERANCA DO SUL', 'BOITUVA', 'JACI', 'RIO GRANDE DA SERRA',
       'VARGEM', 'SANTO EXPEDITO', 'SAO PEDRO DO TURVO',
       'RIBEIRAO BONITO', 'CORONEL MACEDO', 'QUATA', 'JUMIRIM',
       'DIVINOLANDIA', 'PROMISSAO', 'MIRANTE DO PARANAPANEMA', 'IPORANGA',
       'PARIQUERA-ACU', 'SALES OLIVEIRA', 'BURITIZAL', 'APIAI',
       'ESPIRITO SANTO DO TURVO', 'SAO JOSE DO RIO PARDO',
       'CASSIA DOS COQUEIROS', 'SANTO ANTONIO DO ARACANGUA',
       'MIRASSOLANDIA', 'AMERICO BRASILIENSE', 'PARAIBUNA', 'DUARTINA',
       'IPAUSSU', 'LUIS ANTONIO', 'GUARACI', 'SANTO ANTONIO DO JARDIM',
       'AREIOPOLIS', 'POA', 'CAFELANDIA', 'CONCHAS', 'CORUMBATAI',
       'ALFREDO MARCONDES', 'CAMPOS NOVOS PAULISTA', 'SETE BARRAS',
       'PONGAI', 'MOMBUCA', 'GAVIAO PEIXOTO', 'PANORAMA',
       'AMERICO DE CAMPOS', 'GETULINA', 'JUNQUEIROPOLIS', 'TAPIRAI',
       'SANTO ANASTACIO', 'ITAPIRAPUA PAULISTA', 'ROSANA', 'ITAPORANGA',
       'MANDURI', 'TAQUARAL', 'AGUDOS', 'NUPORANGA', 'GUARANTA',
       'CASA BRANCA', 'CANDIDO MOTA', 'BASTOS', 'GALIA', 'CARDOSO',
       'IGARAPAVA', 'NEVES PAULISTA', 'PARDINHO', 'BRAUNA',
       'SAO JOAQUIM DA BARRA', 'VARGEM GRANDE PAULISTA', 'NARANDIBA',
       'PALESTINA', 'TRABIJU', 'GUAIMBE', 'MINEIROS DO TIETE', 'BARIRI',
       'AGUAS DE SANTA BARBARA', 'PITANGUEIRAS', 'PLANALTO', 'CRUZEIRO',
       'MERIDIANO', 'FARTURA', 'DOURADO', 'IARAS', 'ORINDIUVA',
       'CABRALIA PAULISTA', 'BIRITIBA MIRIM', 'BORACEIA', 'MONCOES',
       'COROADOS', 'BURITAMA', 'PRESIDENTE BERNARDES', 'INDIAPORA',
       'IRACEMAPOLIS', 'POTIRENDABA', 'GLICERIO', 'MONTE ALEGRE DO SUL',
       'HERCULANDIA', 'TAGUAI', 'CACONDE', 'BALSAMO', 'TURMALINA',
       'ILHA COMPRIDA', 'TEJUPA', 'NANTES', 'GUARA', 'TAMBAU',
       'CAMPINA DO MONTE ALEGRE', 'FERNANDO PRESTES', 'SANTA LUCIA',
       'CASTILHO', 'VISTA ALEGRE DO ALTO', 'OLEO', 'POLONI', 'TURIUBA',
       'CANAS', 'MARAPOAMA', 'PAULO DE FARIA', 'PAULICEIA',
       'BERNARDINO DE CAMPOS', 'IBIRAREMA', 'PEDRA BELA', 'LUTECIA',
       'PALMARES PAULISTA', 'ALTINOPOLIS', 'NOVA LUZITANIA', 'MENDONCA',
       'BOREBI', 'SANTA CRUZ DA CONCEICAO', 'AVAI', 'VERA CRUZ',
       'OURO VERDE', 'ARIRANHA', 'CATIGUA', 'TACIBA', 'MORUNGABA',
       'OUROESTE', 'VIRADOURO', 'REDENCAO DA SERRA', 'RINCAO',
       'SUZANAPOLIS', 'UNIAO PAULISTA', 'SANTA ERNESTINA', 'LAVINIA',
       'ITABERA', 'TUPI PAULISTA', 'INUBIA PAULISTA', 'ANGATUBA',
       'QUADRA', 'IRAPURU', 'HOLAMBRA', 'SANTA RITA D OESTE', 'DOBRADA',
       'MARINOPOLIS', 'ALVARO DE CARVALHO', 'COLOMBIA', 'UBIRAJARA',
       'LINDOIA', 'NOVA CAMPINA', 'ANALANDIA', 'REGINOPOLIS',
       'LUCIANOPOLIS', 'IPEUNA', 'RAFARD', 'PARAISO', 'MONTEIRO LOBATO',
       'POTIM', 'FLORIDA PAULISTA', 'SAO JOAO DE IRACEMA', 'ORIENTE',
       'RIFAINA', 'SANTANA DA PONTE PENSA', 'AREIAS', 'ALVARES FLORENCE',
       'CAIUA', 'PIACATU', 'JERIQUARA', 'DIRCE REIS', 'BALBINOS',
       'EMBAUBA', 'CANITAR', 'MOTUCA', 'OSCAR BRESSANE', 'SANTA BRANCA',
       'SUD MENNUCCI', 'URU', 'MARIAPOLIS', 'SEBASTIANOPOLIS DO SUL',
       'MURUTINGA DO SUL', 'PIQUEROBI', 'JOAO RAMALHO',
       'PEDRINHAS PAULISTA', 'ASPASIA', 'ESTIVA GERBI', 'LAGOINHA',
       'ITAPUI', 'RIVERSUL', 'RIBEIRAO CORRENTE', 'MACAUBAL', 'SARUTAIA',
       'SAO BENTO DO SAPUCAI', 'TAIUVA', 'BREJO ALEGRE',
       'NOVA CANAA PAULISTA', 'LUPERCIO', 'NOVA ALIANCA', 'SABINO',
       'NOVA GUATAPORANGA', 'PARISI', 'ALTAIR', 'PRATANIA', 'PARANAPUA',
       'RIBEIRAO GRANDE', 'IEPE', 'GUARACAI', 'TAIACU', 'VALPARAISO',
       'MONTE CASTELO', 'PONTES GESTAL', 'SANTA ALBERTINA', 'SANDOVALINA',
       'MACEDONIA', 'PAULISTANIA', 'NOVA INDEPENDENCIA', 'SANTA MERCEDES',
       'CANDIDO RODRIGUES', 'SANTOPOLIS DO AGUAPEI', 'LUIZIANIA',
       'RIBEIRAO DO SUL', 'QUEIROZ', 'ITAPURA', 'CAIABU', 'TARABAI',
       'RUBINEIA', 'MIRA ESTRELA', 'SAO JOAO DAS DUAS PONTES', 'BORA',
       'GABRIEL MONTEIRO', 'ITAJU', 'APARECIDA D OESTE', 'MESOPOLIS',
       'SANTA SALETE', 'GASTAO VIDIGAL', 'BARAO DE ANTONINA',
       'JULIO MESQUITA', 'SALMOURAO', 'DOLCINOPOLIS', 'RUBIACEA', 'MAGDA',
       'SAO JOAO DO PAU D ALHO', 'ARAPEI', 'ALVINLANDIA',
       'SAO JOSE DO BARREIRO', 'ARCO-IRIS', 'FERNAO', 'FLORA RICA',
       'GUARANI D OESTE', 'AGUAS DE SAO PEDRO', 'CRUZALIA', 'LOURDES',
       'ITAOCA', 'PRESIDENTE ALVES'], dtype=object)

In [65]:
sp_acidentes_fatais = acid_fatais[acid_fatais['Município'] == "SAO PAULO"]

In [68]:
loc_acidentes_fatais = sp_acidentes_fatais[['Lat (GEO)','Long (GEO)']]

In [77]:
#Ver como jogar todas as coordenadas no mapa depois
import folium

m = folium.Map(location=[45.372, -121.6972], zoom_start=12, tiles="Stamen Terrain")

tooltip = "Acidente!"

for i,j in loc_acidentes_fatais['Lat (GEO)'],loc_acidentes_fatais['Long (GEO)']:
    folium.Marker(
        [i, j], tooltip=tooltip
    ).add_to(m)

ValueError: too many values to unpack (expected 2)